### ISSUE TITLE
[SITE][DOCS] Launch Checklist

### ISSUE THREAD

**Issue by celestehorgan** [o3de/o3de.org#578]
- [x] Remove password from Netlify (via Netlify console)
- [x] Homepage content needs completion
- [x] Logo wall needs completion
- [x] Download page needs content
- [x] Community page/blog needs content 
- [x] Remove test blog posts
- [x] Ensure all docs pages have a `title` frontmatter
- [x] Ensure o3de.org domain points where it needs to go
- [x] Social media accounts need to be linked
- [x] Repositories like this one need to be un-privated
- [x] Add a `LICENSE` and `LICENSE-docs`file 
- [x] Remove features from Kitchen Sink/Smoketest which are removed before launch

**Comment by sptramer** [comment]
@erickson-doug Is this closed out? I'm going to assume "yes".
